ENTRANCE_PHOTO_ID = "AgACAgIAAxkBAAIBZGXyDYIkKcIfH_YNHMualqx7CkajAAJN2TEb-J2RS6m_21jnyr0bAQADAgADeQADNAQ"

MOSCOW_IN_PERSON_INFO = [
    "AgACAgIAAxkBAAIBm2XyFNXP2_NAKc4dp2uQJWDaoAKdAAJs2TEb-J2RS3stjPGo7122AQADAgADeQADNAQ"
]

VOTING_IN_MOSCOW_DEG = [
    "AgACAgIAAxkBAAIBdWXyEri3G_48DX0u7v86fdAuZs_5AAJc2TEb-J2RS8DHz58wyZUaAQADAgADeQADNAQ",
    "AgACAgIAAxkBAAIBdmXyEwUd5eb-KZ05yUCokF4NQClVAAJd2TEb-J2RSwnomGATpyxaAQADAgADeQADNAQ",
    "AgACAgIAAxkBAAIBu2XyFxXjcapmo7-Syy1WvUYpZvjgAAJ12TEb-J2RS0gm4CRUVE9rAQADAgADeAADNAQ",
]

VOTING_IN_REGION_DEG = [
    "AgACAgIAAxkBAAIBw2XyGHfscmlXLjsAAdsheAT4KTaZ5wACc9kxG_idkUv0-ypRNZby5gEAAwIAA3kAAzQE"
]
