{
 "title": "Результаты голосования на ДЭГ в Москве",
 "time": { "from": "2024-03-15T05:00:00.000Z", "to": "2024-03-17T17:00:00.000Z" },
 "panels": [
  {
   "title": "Статистика голосования, финал",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with pivoted_table as (\r\n  select\r\n    *\r\n  from\r\n    crosstab(\r\n      'SELECT\r\n    tx_source, tx_type,\r\n  \tsum(transaction_cnt) as cnt\r\nFROM\r\n  store_issue_ballot_by_time\r\nWHERE tx_time < TIMESTAMP WITH TIME ZONE ''2024-03-18 21:00:00+03''\r\nGROUP BY\r\n  tx_type, tx_source\r\nORDER BY 1, 2',\r\n      'SELECT unnest(ARRAY[''issueBallot'', ''storeBallot''])'\r\n    ) as final_result(\r\n      tx_source text,\r\n      issueBallot int,\r\n      storeBallot int\r\n    )\r\n),\r\npivoted_table_with_paper AS (\r\n  SELECT\r\n    *\r\n  FROM\r\n    pivoted_table\r\n  UNION\r\n  ALL (\r\n    SELECT\r\n      'Бумага' as tx_source,\r\n      5407471 - SUM(issueBallot) as issueBallot,\r\n      null as storeBallot\r\n    FROM\r\n      pivoted_table\r\n  )\r\n),\r\ntable_query as (\r\n  select\r\n    case\r\n      when \"tx_source\" = '\"DEG\"' then 'ДЭГ'\r\n      when \"tx_source\" = '\"EVT\"' then 'ТЭГ'\r\n      else \"tx_source\"\r\n    end as \"Тип голосования\",\r\n    issueBallot as \"Выданно бюллетеней\"\r\n  from\r\n    pivoted_table_with_paper\r\n)\r\nSELECT\r\n  *\r\nFROM\r\n  table_query;"
    }
   ]
  },
  {
   "title": "% кандидатов, ДЭГ + ТЭГ",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH candidate_id_to_votes AS (\r\n  SELECT\r\n    candidate_id,\r\n    SUM(cnt) as candidate_votes\r\n  FROM\r\n    time_to_candidate_minute_trunc\r\n  GROUP BY\r\n    candidate_id\r\n),\r\ncandidate_name_to_votes AS (\r\n  SELECT\r\n    candidate_id_to_votes.*,\r\n    candidate_id_to_name.candidate_name as candidate_name\r\n  FROM\r\n    candidate_id_to_votes\r\n    LEFT JOIN candidate_id_to_name ON (\r\n      candidate_id_to_votes.candidate_id :: text = candidate_id_to_name.candidate_id :: text\r\n    )\r\n)\r\nSELECT\r\n  COALESCE(candidate_name :: text, 'Испорченный бюллетень') as candidate_name,\r\n  candidate_votes\r\nFROM\r\n  candidate_name_to_votes;"
    }
   ]
  },
  {
   "title": "% кандидатов, ДЭГ",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH candidate_id_to_votes AS (\r\n  SELECT\r\n    candidate_id,\r\n    SUM(cnt) as candidate_votes\r\n  FROM\r\n    time_to_candidate_minute_trunc\r\n  WHERE source = 'DEG'\r\n  GROUP BY\r\n    candidate_id\r\n),\r\ncandidate_name_to_votes AS (\r\n  SELECT\r\n    candidate_id_to_votes.*,\r\n    candidate_id_to_name.candidate_name as candidate_name\r\n  FROM\r\n    candidate_id_to_votes\r\n    LEFT JOIN candidate_id_to_name ON (\r\n      candidate_id_to_votes.candidate_id :: text = candidate_id_to_name.candidate_id :: text\r\n    )\r\n)\r\nSELECT\r\n  COALESCE(candidate_name :: text, 'Испорченный бюллетень') as candidate_name,\r\n  candidate_votes\r\nFROM\r\n  candidate_name_to_votes;"
    }
   ]
  },
  {
   "title": "% кандидатов, ТЭГ",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH candidate_id_to_votes AS (\r\n  SELECT\r\n    candidate_id,\r\n    SUM(cnt) as candidate_votes\r\n  FROM\r\n    time_to_candidate_minute_trunc\r\n  WHERE source = 'EVT'\r\n  GROUP BY\r\n    candidate_id\r\n),\r\ncandidate_name_to_votes AS (\r\n  SELECT\r\n    candidate_id_to_votes.*,\r\n    candidate_id_to_name.candidate_name as candidate_name\r\n  FROM\r\n    candidate_id_to_votes\r\n    LEFT JOIN candidate_id_to_name ON (\r\n      candidate_id_to_votes.candidate_id :: text = candidate_id_to_name.candidate_id :: text\r\n    )\r\n)\r\nSELECT\r\n  COALESCE(candidate_name :: text, 'Испорченный бюллетень') as candidate_name,\r\n  candidate_votes\r\nFROM\r\n  candidate_name_to_votes;"
    }
   ]
  },
  {
   "title": "Количество проголосовавших в разбивке ДЭГ/ТЭГ",
   "type": "timeseries",
   "description": "DEG: Электронное голосование\nEVT: Голосование в терминале",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tx_time,'5m'),\n  sum(transaction_cnt) AS \"value\",\n  tx_source as \"metric\"\nFROM store_issue_ballot_by_time\nWHERE\n  $__timeFilter(tx_time) and tx_type = 'storeBallot'\nGROUP BY time, tx_source\nORDER BY time"
    }
   ]
  },
  {
   "title": "% кандидатов, ДЭГ + ТЭГ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH time_candidate_id_to_total AS (\r\n  SELECT\r\n    $__timeGroupAlias(\"storage_timestamp\", '5m'),\r\n    candidate_id,\r\n    SUM(cnt) as candidate_total\r\n  FROM\r\n    time_to_candidate_minute_trunc as t\r\n  WHERE $__timeFilter(\"storage_timestamp\")\r\n  GROUP BY\r\n    time,\r\n    candidate_id\r\n  ORDER BY\r\n    time,\r\n    candidate_id\r\n),\r\ntime_to_total_votes AS (\r\n  SELECT\r\n    time,\r\n    SUM(candidate_total) as total_votes_at_time\r\n  FROM\r\n    time_candidate_id_to_total\r\n  GROUP BY\r\n    time\r\n),\r\ntime_candidate_to_total_joined AS (\r\n  SELECT\r\n    time_candidate_id_to_total.time as time,\r\n    time_candidate_id_to_total.candidate_id as candidate_id,\r\n    time_candidate_id_to_total.candidate_total / time_to_total_votes.total_votes_at_time as candidate_fraction\r\n  FROM\r\n    time_candidate_id_to_total\r\n    JOIN time_to_total_votes USING (time)\r\n),\r\npercents_with_names AS (\r\n  SELECT\r\n    t1.*,\r\n    t2.candidate_name as candidate_name\r\n  FROM\r\n    time_candidate_to_total_joined as t1\r\n    LEFT JOIN candidate_id_to_name as t2 ON (\r\n      t1.candidate_id :: text = t2.candidate_id :: text\r\n    )\r\n)\r\nSELECT\r\n  time,\r\n  COALESCE(candidate_name::text, 'Испорченный бюллетень') as \"metric\",\r\n  candidate_fraction * 100.0 as \"value\"\r\nFROM\r\n  percents_with_names\r\nORDER BY time, candidate_id;"
    }
   ]
  },
  {
   "title": "% кандидатов, ДЭГ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "WITH time_candidate_id_to_total AS (\r\n  SELECT\r\n    $__timeGroupAlias(\"storage_timestamp\", '5m'),\r\n    candidate_id,\r\n    SUM(cnt) as candidate_total\r\n  FROM\r\n    time_to_candidate_minute_trunc as t\r\n  WHERE\r\n    $__timeFilter(\"storage_timestamp\")\r\n    and source = 'DEG'\r\n  GROUP BY\r\n    time,\r\n    candidate_id\r\n  ORDER BY\r\n    time,\r\n    candidate_id\r\n),\r\ntime_to_total_votes AS (\r\n  SELECT\r\n    time,\r\n    SUM(candidate_total) as total_votes_at_time\r\n  FROM\r\n    time_candidate_id_to_total\r\n  GROUP BY\r\n    time\r\n),\r\ntime_candidate_to_total_joined AS (\r\n  SELECT\r\n    time_candidate_id_to_total.time as time,\r\n    time_candidate_id_to_total.candidate_id as candidate_id,\r\n    time_candidate_id_to_total.candidate_total / time_to_total_votes.total_votes_at_time as candidate_fraction\r\n  FROM\r\n    time_candidate_id_to_total\r\n    JOIN time_to_total_votes USING (time)\r\n),\r\npercents_with_names AS (\r\n  SELECT\r\n    t1.*,\r\n    t2.candidate_name as candidate_name\r\n  FROM\r\n    time_candidate_to_total_joined as t1\r\n    LEFT JOIN candidate_id_to_name as t2 ON (\r\n      t1.candidate_id :: text = t2.candidate_id :: text\r\n    )\r\n)\r\nSELECT\r\n  time,\r\n  COALESCE(candidate_name :: text, 'Испорченный бюллетень') as \"metric\",\r\n  candidate_fraction * 100.0 as \"value\"\r\nFROM\r\n  percents_with_names\r\nORDER BY\r\n  time,\r\n  candidate_id;"
    }
   ]
  },
  {
   "title": "% кандидатов, ТЭГ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "WITH time_candidate_id_to_total AS (\r\n  SELECT\r\n    $__timeGroupAlias(\"storage_timestamp\", '5m'),\r\n    candidate_id,\r\n    SUM(cnt) as candidate_total\r\n  FROM\r\n    time_to_candidate_minute_trunc as t\r\n  WHERE\r\n    $__timeFilter(\"storage_timestamp\")\r\n    and source = 'EVT'\r\n  GROUP BY\r\n    time,\r\n    candidate_id\r\n  ORDER BY\r\n    time,\r\n    candidate_id\r\n),\r\ntime_to_total_votes AS (\r\n  SELECT\r\n    time,\r\n    SUM(candidate_total) as total_votes_at_time\r\n  FROM\r\n    time_candidate_id_to_total\r\n  GROUP BY\r\n    time\r\n),\r\ntime_candidate_to_total_joined AS (\r\n  SELECT\r\n    time_candidate_id_to_total.time as time,\r\n    time_candidate_id_to_total.candidate_id as candidate_id,\r\n    (case\r\n      when time_to_total_votes.total_votes_at_time < 15 then null\r\n      else time_candidate_id_to_total.candidate_total / time_to_total_votes.total_votes_at_time\r\n    end) as candidate_fraction\r\n  FROM\r\n    time_candidate_id_to_total\r\n    JOIN time_to_total_votes USING (time)\r\n),\r\npercents_with_names AS (\r\n  SELECT\r\n    t1.*,\r\n    t2.candidate_name as candidate_name\r\n  FROM\r\n    time_candidate_to_total_joined as t1\r\n    LEFT JOIN candidate_id_to_name as t2 ON (\r\n      t1.candidate_id :: text = t2.candidate_id :: text\r\n    )\r\n),\r\ngraph as (\r\n  SELECT\r\n    time,\r\n    COALESCE(candidate_name :: text, 'Испорченный бюллетень') as \"metric\",\r\n    candidate_fraction * 100.0 as \"value\"\r\n  FROM\r\n    percents_with_names\r\n  ORDER BY\r\n    time,\r\n    candidate_id\r\n)\r\nselect\r\n  *\r\nfrom\r\n  graph;"
    }
   ]
  }
 ]
}