{
 "title": "Московский ДЭГ 2024",
 "description": "Смотрим на состояние",
 "time": { "from": "2024-03-15T11:13:26.103Z", "to": "2024-03-15T23:13:26.103Z" },
 "panels": [
  { "title": "Текущие сведения о голосовании", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Статистика голосования на текущий момент",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "with pivoted_table as (\r\nselect\r\n\t*\r\nfrom\r\n\tcrosstab(\r\n  'SELECT\r\n    tx_source, tx_type,\r\n  \tsum(transaction_cnt) as cnt\r\nFROM\r\n  store_issue_ballot_by_time\r\nGROUP BY\r\n  tx_type, tx_source\r\nORDER BY 1, 2',\r\n\t'SELECT unnest(ARRAY[''issueBallot'', ''storeBallot''])'\r\n) as final_result(tx_source text,\r\n\tissueBallot int,\r\n\tstoreBallot int))\r\nselect\r\n\tcase\r\n\t\twhen \"tx_source\" = '\"DEG\"' then 'ДЭГ'\r\n\t\twhen \"tx_source\" = '\"EVT\"' then 'ТЭГ'\r\n\tend as \"Тип голосования\",\r\n\tissueBallot as \"Выданно бюллетеней\",\r\n\tstoreBallot as \"Принято бюллетеней\",\r\n\tissueBallot / 7888635.0 * 100 as \"Явка, %\",\r\n\t(1 - cast(storeBallot as float) / issueBallot) * 100 as \"Унесли «домой», %\"\r\nfrom \r\n\tpivoted_table;"
    }
   ]
  },
  {
   "title": "Количество получивших бюллетени и проголосовавших (агрегация 5 минут)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tx_time,'5m'),\n  sum(transaction_cnt) AS \"value\",\n  tx_type as \"metric\"\nFROM store_issue_ballot_by_time\nWHERE\n  $__timeFilter(tx_time)\nGROUP BY time, tx_type\nORDER BY time"
    }
   ]
  },
  {
   "title": "Количество проголосовавших (ТЭГ)",
   "type": "timeseries",
   "description": "EVT: Голосование в терминале",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tx_time, '5m'),\n  sum(transaction_cnt) AS \"value\"\nFROM\n  store_issue_ballot_by_time\nWHERE\n  $__timeFilter(tx_time)\n  and (tx_type = 'storeBallot')\n  and (tx_source = '\"EVT\"')\nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Количество проголосовавших в разбивке ДЭГ/ТЭГ",
   "type": "timeseries",
   "description": "DEG: Электронное голосование\nEVT: Голосование в терминале",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tx_time,'5m'),\n  sum(transaction_cnt) AS \"value\",\n  tx_source as \"metric\"\nFROM store_issue_ballot_by_time\nWHERE\n  $__timeFilter(tx_time) and tx_type = 'storeBallot'\nGROUP BY time, tx_source\nORDER BY time"
    }
   ]
  },
  {
   "title": "Статистика голосования + ГАС Выборы",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Статистика голосования (15.03.2024 20:00)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with pivoted_table as (\r\n  select\r\n    *\r\n  from\r\n    crosstab(\r\n      'SELECT\r\n    tx_source, tx_type,\r\n  \tsum(transaction_cnt) as cnt\r\nFROM\r\n  store_issue_ballot_by_time\r\nWHERE tx_time < TIMESTAMP WITH TIME ZONE ''2024-03-15 20:00:00+03''\r\nGROUP BY\r\n  tx_type, tx_source\r\nORDER BY 1, 2',\r\n      'SELECT unnest(ARRAY[''issueBallot'', ''storeBallot''])'\r\n    ) as final_result(\r\n      tx_source text,\r\n      issueBallot int,\r\n      storeBallot int\r\n    )\r\n),\r\npivoted_table_with_paper AS (\r\n  SELECT\r\n    *\r\n  FROM\r\n    pivoted_table\r\n  UNION\r\n  ALL (\r\n    SELECT\r\n      'Бумага' as tx_source,\r\n      2976986 - SUM(issueBallot) as issueBallot,\r\n      null as storeBallot\r\n    FROM\r\n      pivoted_table\r\n  )\r\n),\r\ntable_query as (\r\n  select\r\n    case\r\n      when \"tx_source\" = '\"DEG\"' then 'ДЭГ'\r\n      when \"tx_source\" = '\"EVT\"' then 'ТЭГ'\r\n      else \"tx_source\"\r\n    end as \"Тип голосования\",\r\n    issueBallot as \"Выданно бюллетеней\"\r\n  from\r\n    pivoted_table_with_paper\r\n)\r\nSELECT\r\n  *\r\nFROM\r\n  table_query;"
    }
   ]
  },
  {
   "title": "Статистика голосования (16.03.2024 20:00)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with pivoted_table as (\r\n  select\r\n    *\r\n  from\r\n    crosstab(\r\n      'SELECT\r\n    tx_source, tx_type,\r\n  \tsum(transaction_cnt) as cnt\r\nFROM\r\n  store_issue_ballot_by_time\r\nWHERE tx_time < TIMESTAMP WITH TIME ZONE ''2024-03-16 20:00:00+03''\r\nGROUP BY\r\n  tx_type, tx_source\r\nORDER BY 1, 2',\r\n      'SELECT unnest(ARRAY[''issueBallot'', ''storeBallot''])'\r\n    ) as final_result(\r\n      tx_source text,\r\n      issueBallot int,\r\n      storeBallot int\r\n    )\r\n),\r\npivoted_table_with_paper AS (\r\n  SELECT\r\n    *\r\n  FROM\r\n    pivoted_table\r\n  UNION\r\n  ALL (\r\n    SELECT\r\n      'Бумага' as tx_source,\r\n      4286481 - SUM(issueBallot) as issueBallot,\r\n      null as storeBallot\r\n    FROM\r\n      pivoted_table\r\n  )\r\n),\r\ntable_query as (\r\n  select\r\n    case\r\n      when \"tx_source\" = '\"DEG\"' then 'ДЭГ'\r\n      when \"tx_source\" = '\"EVT\"' then 'ТЭГ'\r\n      else \"tx_source\"\r\n    end as \"Тип голосования\",\r\n    issueBallot as \"Выданно бюллетеней\"\r\n  from\r\n    pivoted_table_with_paper\r\n)\r\nSELECT\r\n  *\r\nFROM\r\n  table_query;"
    }
   ]
  },
  {
   "title": "Статистика голосования (17.03.2024, 15:00)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with pivoted_table as (\r\n  select\r\n    *\r\n  from\r\n    crosstab(\r\n      'SELECT\r\n    tx_source, tx_type,\r\n  \tsum(transaction_cnt) as cnt\r\nFROM\r\n  store_issue_ballot_by_time\r\nWHERE tx_time < TIMESTAMP WITH TIME ZONE ''2024-03-17 15:00:00+03''\r\nGROUP BY\r\n  tx_type, tx_source\r\nORDER BY 1, 2',\r\n      'SELECT unnest(ARRAY[''issueBallot'', ''storeBallot''])'\r\n    ) as final_result(\r\n      tx_source text,\r\n      issueBallot int,\r\n      storeBallot int\r\n    )\r\n),\r\npivoted_table_with_paper AS (\r\n  SELECT\r\n    *\r\n  FROM\r\n    pivoted_table\r\n  UNION\r\n  ALL (\r\n    SELECT\r\n      'Бумага' as tx_source,\r\n      4998214 - SUM(issueBallot) as issueBallot,\r\n      null as storeBallot\r\n    FROM\r\n      pivoted_table\r\n  )\r\n),\r\ntable_query as (\r\n  select\r\n    case\r\n      when \"tx_source\" = '\"DEG\"' then 'ДЭГ'\r\n      when \"tx_source\" = '\"EVT\"' then 'ТЭГ'\r\n      else \"tx_source\"\r\n    end as \"Тип голосования\",\r\n    issueBallot as \"Выданно бюллетеней\"\r\n  from\r\n    pivoted_table_with_paper\r\n)\r\nSELECT\r\n  *\r\nFROM\r\n  table_query;"
    }
   ]
  },
  {
   "title": "Статистика голосования, финал",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with pivoted_table as (\r\n  select\r\n    *\r\n  from\r\n    crosstab(\r\n      'SELECT\r\n    tx_source, tx_type,\r\n  \tsum(transaction_cnt) as cnt\r\nFROM\r\n  store_issue_ballot_by_time\r\nWHERE tx_time < TIMESTAMP WITH TIME ZONE ''2024-03-18 21:00:00+03''\r\nGROUP BY\r\n  tx_type, tx_source\r\nORDER BY 1, 2',\r\n      'SELECT unnest(ARRAY[''issueBallot'', ''storeBallot''])'\r\n    ) as final_result(\r\n      tx_source text,\r\n      issueBallot int,\r\n      storeBallot int\r\n    )\r\n),\r\npivoted_table_with_paper AS (\r\n  SELECT\r\n    *\r\n  FROM\r\n    pivoted_table\r\n  UNION\r\n  ALL (\r\n    SELECT\r\n      'Бумага' as tx_source,\r\n      5407471 - SUM(issueBallot) as issueBallot,\r\n      null as storeBallot\r\n    FROM\r\n      pivoted_table\r\n  )\r\n),\r\ntable_query as (\r\n  select\r\n    case\r\n      when \"tx_source\" = '\"DEG\"' then 'ДЭГ'\r\n      when \"tx_source\" = '\"EVT\"' then 'ТЭГ'\r\n      else \"tx_source\"\r\n    end as \"Тип голосования\",\r\n    issueBallot as \"Выданно бюллетеней\"\r\n  from\r\n    pivoted_table_with_paper\r\n)\r\nSELECT\r\n  *\r\nFROM\r\n  table_query;"
    }
   ]
  },
  {
   "title": "Статистика голосования (16.03.2024 20:00)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "with pivoted_table as (\r\n  select\r\n    *\r\n  from\r\n    crosstab(\r\n      'SELECT\r\n    tx_source, tx_type,\r\n  \tsum(transaction_cnt) as cnt\r\nFROM\r\n  store_issue_ballot_by_time\r\nWHERE tx_time < TIMESTAMP WITH TIME ZONE ''2024-03-16 20:00:00+03''\r\nGROUP BY\r\n  tx_type, tx_source\r\nORDER BY 1, 2',\r\n      'SELECT unnest(ARRAY[''issueBallot'', ''storeBallot''])'\r\n    ) as final_result(\r\n      tx_source text,\r\n      issueBallot int,\r\n      storeBallot int\r\n    )\r\n),\r\npivoted_table_with_paper AS (\r\n  SELECT\r\n    *\r\n  FROM\r\n    pivoted_table\r\n  UNION\r\n  ALL (\r\n    SELECT\r\n      'Бумага' as tx_source,\r\n      4286481 - SUM(issueBallot) as issueBallot,\r\n      null as storeBallot\r\n    FROM\r\n      pivoted_table\r\n  )\r\n),\r\ntable_query as (\r\n  select\r\n    case\r\n      when \"tx_source\" = '\"DEG\"' then 'ДЭГ'\r\n      when \"tx_source\" = '\"EVT\"' then 'ТЭГ'\r\n      else \"tx_source\"\r\n    end as \"Тип голосования\",\r\n    issueBallot as \"Выданно бюллетеней\",\r\n    storeBallot as \"Принято бюллетеней\",\r\n    issueBallot / 7888635.0 * 100 as \"Явка, %\",\r\n    (1 - cast(storeBallot as float) / issueBallot) * 100 as \"Унесли «домой», %\"\r\n  from\r\n    pivoted_table_with_paper\r\n)\r\nSELECT\r\n  *\r\nFROM\r\n  table_query;"
    }
   ]
  },
  {
   "title": "Статистика голосования (15.03.2024 20:00)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "with pivoted_table as (\r\n  select\r\n    *\r\n  from\r\n    crosstab(\r\n      'SELECT\r\n    tx_source, tx_type,\r\n  \tsum(transaction_cnt) as cnt\r\nFROM\r\n  store_issue_ballot_by_time\r\nWHERE tx_time < TIMESTAMP WITH TIME ZONE ''2024-03-15 20:00:00+03''\r\nGROUP BY\r\n  tx_type, tx_source\r\nORDER BY 1, 2',\r\n      'SELECT unnest(ARRAY[''issueBallot'', ''storeBallot''])'\r\n    ) as final_result(\r\n      tx_source text,\r\n      issueBallot int,\r\n      storeBallot int\r\n    )\r\n),\r\npivoted_table_with_paper AS (\r\n  SELECT\r\n    *\r\n  FROM\r\n    pivoted_table\r\n  UNION\r\n  ALL (\r\n    SELECT\r\n      'Бумага' as tx_source,\r\n      2976986 - SUM(issueBallot) as issueBallot,\r\n      null as storeBallot\r\n    FROM\r\n      pivoted_table\r\n  )\r\n),\r\ntable_query as (\r\n  select\r\n    case\r\n      when \"tx_source\" = '\"DEG\"' then 'ДЭГ'\r\n      when \"tx_source\" = '\"EVT\"' then 'ТЭГ'\r\n      else \"tx_source\"\r\n    end as \"Тип голосования\",\r\n    issueBallot as \"Выданно бюллетеней\",\r\n    storeBallot as \"Принято бюллетеней\",\r\n    issueBallot / 7888635.0 * 100 as \"Явка, %\",\r\n    (1 - cast(storeBallot as float) / issueBallot) * 100 as \"Унесли «домой», %\"\r\n  from\r\n    pivoted_table_with_paper\r\n)\r\nSELECT\r\n  *\r\nFROM\r\n  table_query;"
    }
   ]
  }
 ]
}